from typing import Any


def builtin_rules() -> list[dict[str, Any]]:
    return [
        {
            "name": "Multiple failed login attempts from same IP",
            "description": "Detects repeated authentication failures from one source IP.",
            "severity": "high",
            "enabled": True,
            "conditions_json": {"type": "threshold", "filters": {"event_type": "failed_login"}, "group_by": ["source_ip"]},
            "time_window_minutes": 10,
            "threshold": 5,
        },
        {
            "name": "Successful login after failed attempts",
            "description": "Detects a successful login following several failures from the same IP and user.",
            "severity": "critical",
            "enabled": True,
            "conditions_json": {"type": "sequence_success_after_failures"},
            "time_window_minutes": 15,
            "threshold": 3,
        },
        {
            "name": "Suspicious admin login",
            "description": "Flags successful privileged account logins for analyst review.",
            "severity": "high",
            "enabled": True,
            "conditions_json": {
                "type": "threshold",
                "filters": {"event_type": "successful_login", "username_in": ["admin", "root", "administrator"]},
                "group_by": ["username", "source_ip"],
            },
            "time_window_minutes": 30,
            "threshold": 1,
        },
        {
            "name": "Login attempt from unusual country",
            "description": "Detects authentication attempts from countries outside the expected demo baseline.",
            "severity": "medium",
            "enabled": True,
            "conditions_json": {
                "type": "threshold",
                "filters": {"event_category": "authentication", "geo_country_not_in": ["US", "TR", "DE"]},
                "group_by": ["source_ip", "geo_country"],
            },
            "time_window_minutes": 20,
            "threshold": 1,
        },
        {
            "name": "High number of 404 responses",
            "description": "Detects many HTTP 404 responses from a single source IP.",
            "severity": "medium",
            "enabled": True,
            "conditions_json": {"type": "threshold", "filters": {"status_code": 404}, "group_by": ["source_ip"]},
            "time_window_minutes": 10,
            "threshold": 10,
        },
        {
            "name": "Possible directory brute force",
            "description": "Detects repeated misses and sensitive path probing from one source IP.",
            "severity": "high",
            "enabled": True,
            "conditions_json": {
                "type": "threshold",
                "filters": {"event_category": "web", "status_code_range": [400, 499]},
                "group_by": ["source_ip"],
            },
            "time_window_minutes": 10,
            "threshold": 15,
        },
        {
            "name": "Repeated sensitive path access",
            "description": "Detects repeated requests to paths such as /admin, /login, /wp-admin, and /.env.",
            "severity": "high",
            "enabled": True,
            "conditions_json": {
                "type": "threshold",
                "filters": {"request_path_contains_any": ["/admin", "/login", "/wp-admin", "/.env"]},
                "group_by": ["source_ip"],
            },
            "time_window_minutes": 10,
            "threshold": 4,
        },
        {
            "name": "Large request volume burst",
            "description": "Detects a large number of web requests in a short time window.",
            "severity": "medium",
            "enabled": True,
            "conditions_json": {"type": "threshold", "filters": {"event_category": "web"}, "group_by": ["source_ip"]},
            "time_window_minutes": 5,
            "threshold": 60,
        },
        {
            "name": "Suspicious user agent",
            "description": "Detects tool-like user agents including curl, sqlmap, nikto, and python-requests.",
            "severity": "high",
            "enabled": True,
            "conditions_json": {
                "type": "threshold",
                "filters": {"user_agent_contains_any": ["curl", "sqlmap", "nikto", "python-requests"]},
                "group_by": ["source_ip", "user_agent"],
            },
            "time_window_minutes": 10,
            "threshold": 1,
        },
        {
            "name": "Firewall denied traffic spike",
            "description": "Detects repeated denied firewall events from one source IP.",
            "severity": "medium",
            "enabled": True,
            "conditions_json": {"type": "threshold", "filters": {"event_type": "firewall_denied"}, "group_by": ["source_ip"]},
            "time_window_minutes": 10,
            "threshold": 20,
        },
        {
            "name": "Repeated access from blacklisted indicator",
            "description": "Matches events against the local threat intelligence blacklist.",
            "severity": "critical",
            "enabled": True,
            "conditions_json": {"type": "blacklist"},
            "time_window_minutes": 60,
            "threshold": 1,
        },
    ]

